
@man = Manufacturere.create(name: "American Greetings")
@man = Manufacturere.create(name: "Crane")
@man = Manufacturere.create(name: "Papyrus")
@man = Manufacturere.create(name: "Recycled Paper Greetings")
@man = Manufacturere.create(name: "Carlton Cards")
@man = Manufacturere.create(name: "Hallmark Card")

@aisle = Aisle.create(aisle_number: "1")
@aisle = Aisle.create(aisle_number: "2")
@aisle = Aisle.create(aisle_number: "3")
@aisle = Aisle.create(aisle_number: "4")
@aisle = Aisle.create(aisle_number: "5")
@aisle = Aisle.create(aisle_number: "6")

@occasion = Occasion.create(name_of: "Congratulations cards")
@occasion = Occasion.create(name_of: "Farewell Cards")
@occasion = Occasion.create(name_of: "Friendship Cards")
@occasion = Occasion.create(name_of: "Good Luck Cards")
@occasion = Occasion.create(name_of: "Birthday Cards")
@occasion = Occasion.create(name_of: "Education Cards")
@occasion = Occasion.create(name_of: "Congratulations cards")
@occasion = Occasion.create(name_of: "Congratulations cards")
@occasion = Occasion.create(name_of: "Love cards")
@occasion = Occasion.create(name_of: "New Baby")
@occasion = Occasion.create(name_of: "Valentine's Day")
@occasion = Occasion.create(name_of: "Mother's Day")
@occasion = Occasion.create(name_of: "Father's Day")
@occasion = Occasion.create(name_of: "Spanish Cards")
@occasion = Occasion.create(name_of: "Holidays Cards")
@occasion = Occasion.create(name_of: "Religious Cards")
@occasion = Occasion.create(name_of: "Holiday cards")
@occasion = Occasion.create(name_of: "Christmas cards")


